[package]
authors = ["The wasm-bindgen Developers"]
categories = ["wasm"]
description = """
Easy support for interacting between JS and Rust.
"""
documentation = "https://docs.rs/wasm-bindgen"
edition = "2021"
homepage = "https://wasm-bindgen.github.io/wasm-bindgen"
include = ["/build.rs", "/LICENSE-*", "/src"]
license = "MIT OR Apache-2.0"
name = "not-wasm-bindgen"
readme = "README.md"
repository = "https://github.com/wasm-bindgen/wasm-bindgen"
rust-version = "1.77"
version = "0.2.121"

[package.metadata.docs.rs]
features = ["serde-serialize"]

[lib]
test = false

[features]

[lints]
workspace = true

[workspace.lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = [
  'cfg(wasm_bindgen_unstable_test_coverage)',
  'cfg(wasm_bindgen_use_js_sys)',
  'cfg(xxx_debug_only_print_generated_code)',
] }
unused_lifetimes = "warn"

[workspace.lints.clippy]
large_enum_variant = "allow"
new_without_default = "allow"
overly_complex_bool_expr = "allow"
too_many_arguments = "allow"
type_complexity = "allow"
uninlined_format_args = "warn"

[workspace]
exclude = [
  "benchmarks",
  "crates/cli",
  "crates/msrv/resolver",
  "crates/msrv/lib",
  "crates/msrv/cli",
  "crates/test",
  "crates/test/sample",
  "crates/typescript-tests",
  "crates/webidl",
  "crates/webidl-tests",
  "examples/*",
  "tests/no-std",
]
members = [
  "crates/js-sys",
  "crates/web-sys",
  "crates/futures",
]
resolver = "2"
